packages:
  - example/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.16f3018f31dd475daf775e87e3eeb870fe9e5b4d
  vite-plus: 0.0.0-commit.16f3018f31dd475daf775e87e3eeb870fe9e5b4d
  vitest: 4.1.10
  '@vitest/coverage-v8': 4.1.10

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
  - workerd

overrides:
  kysely: 0.28.17
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
