packages:
  - example/*
  - packages/*
  - sites/*

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.fba044cf40fea5a7bf4a2ee97822f174eab33dfa
  vite-plus: 0.0.0-commit.fba044cf40fea5a7bf4a2ee97822f174eab33dfa
  vitest: 4.1.11
  '@vitest/coverage-v8': 4.1.11

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
  - workerd

overrides:
  '@cloudflare/vite-plugin': 1.54.9
  '@cloudflare/workers-types': 5.20260904.1
  better-auth: 1.7.2
  kysely: 0.28.17
  pg: 8.23.0
  vite@*: 'catalog:'
  vitest@*: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
