name: deploy-docs

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: voidzero-dev/setup-vp@v1.21.1
        with:
          node-version: '24'
          cache: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: vp install && vp run dev:setup

      - name: Build with VitePress
        run: vp run build:all && vp run build:docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
